<?php
require __DIR__.'/bootstrap.php'; require_login(); $me=user();
$accountId=is_admin()?(int)($_GET['account_id']??$me['id']):(int)$me['id'];
if(!$accountId){$accountId=(int)$me['id'];}
$account=$pdo->prepare('SELECT id,name,email,phone,account_no,role FROM users WHERE id=?');$account->execute([$accountId]);$account=$account->fetch();if(!$account){http_response_code(404);exit('Account not found.');}
if(!is_admin()&&$account['id']!=$me['id']){http_response_code(403);exit('Access denied.');}
$q=$pdo->prepare('SELECT * FROM account_transactions WHERE user_id=? ORDER BY transaction_date DESC,id DESC');$q->execute([$accountId]);$rows=$q->fetchAll();$debit=array_sum(array_column($rows,'debit'));$credit=array_sum(array_column($rows,'credit'));$customers=is_admin()?$pdo->query("SELECT id,name,account_no,role FROM users WHERE active=1 ORDER BY name")->fetchAll():[];$title='Account ledger';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><p class="text-primary text-uppercase small fw-bold mb-1">Account ledger</p><h1 class="h3 fw-bold mb-1"><?=e($account['name'])?></h1><p class="text-secondary mb-0">Account No: <strong><?=e($account['account_no'])?></strong></p></div><?php if(is_admin()):?><form method="get"><select class="form-select" name="account_id" onchange="this.form.submit()"><?php foreach($customers as $c):?><option value="<?=$c['id']?>" <?=$c['id']==$accountId?'selected':''?>><?=e($c['name'].' · '.$c['role'].' · '.$c['account_no'])?></option><?php endforeach?></select></form><?php endif?></div>
<div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="card p-3"><small class="text-secondary">Total invoices</small><strong class="h5 mb-0 text-danger"><?=money($debit)?></strong></div></div><div class="col-6 col-lg-3"><div class="card p-3"><small class="text-secondary">Total payments</small><strong class="h5 mb-0 text-success"><?=money($credit)?></strong></div></div><div class="col-12 col-lg-3"><div class="card p-3"><small class="text-secondary">Current balance</small><strong class="h5 mb-0 <?=($debit-$credit)>0?'text-danger':'text-success'?>"><?=money($debit-$credit)?></strong></div></div></div>
<div class="card p-3 p-lg-4"><input class="form-control mb-3" style="max-width:430px" data-table-search placeholder="Search transaction or reference"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Description</th><th class="text-end">Debit</th><th class="text-end">Credit</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=app_date($r['transaction_date'])?></td><td><span class="status <?=$r['transaction_type']==='Payment'?'status-paid':''?>"><?=e($r['transaction_type'])?></span></td><td class="fw-semibold"><?=e($r['reference_no'])?></td><td><?=e($r['description'])?></td><td class="text-end text-danger"><?=money($r['debit'])?></td><td class="text-end text-success"><?=money($r['credit'])?></td></tr><?php endforeach?><?php if(!$rows):?><tr><td colspan="6" class="text-center text-secondary py-5">No transactions have been recorded for this account.</td></tr><?php endif?></tbody></table></div></div>
<?php require __DIR__.'/partials/footer.php'; ?>
