<?php
require __DIR__.'/bootstrap.php';require_perm('bank.manage');$me=user();
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    $scope=is_admin()?'':' AND branch_id='.(int)require_branch();
    $branchId=is_admin()?(int)($_POST['branch_id']??$me['branch_id']):$me['branch_id'];
    if(isset($_POST['create'])){
        $pdo->prepare('INSERT INTO bank_accounts(name,bank_name,account_number,opening_balance,branch_id,created_by) VALUES(?,?,?,?,?,?)')->execute([trim($_POST['name']),trim($_POST['bank_name']),trim($_POST['account_number']),max(0,(float)$_POST['opening_balance']),(int)$branchId,$me['id']]);
        flash('success','Bank account created.');
    }elseif(isset($_POST['update'])){
        $pdo->prepare('UPDATE bank_accounts SET name=?,bank_name=?,account_number=?,opening_balance=?,branch_id=?,active=? WHERE id=?'.$scope)->execute([trim($_POST['name']),trim($_POST['bank_name']),trim($_POST['account_number']),max(0,(float)$_POST['opening_balance']),(int)$branchId,isset($_POST['active'])?1:0,(int)$_POST['id']]);
        flash('success','Bank account updated.');
    }elseif(isset($_POST['delete'])){
        try{$pdo->prepare('DELETE FROM bank_accounts WHERE id=?'.$scope)->execute([(int)$_POST['id']]);flash('success','Bank account deleted.');}
        catch(PDOException $e){flash('danger','This account has linked bank transactions and cannot be deleted. Disable it instead.');}
    }elseif(isset($_POST['toggle'])){
        $pdo->prepare('UPDATE bank_accounts SET active=1-active WHERE id=?'.$scope)->execute([(int)$_POST['id']]);
        flash('success','Bank account status updated.');
    }
    redirect('bank_accounts.php');
}
$scope=is_admin()?'':' WHERE b.branch_id='.(int)require_branch();
$rows=$pdo->query('SELECT b.*,br.name branch_name,COALESCE(SUM(t.amount_in),0) money_in,COALESCE(SUM(t.amount_out),0) money_out FROM bank_accounts b JOIN branches br ON br.id=b.branch_id LEFT JOIN bank_transactions t ON t.bank_account_id=b.id'.$scope.' GROUP BY b.id ORDER BY b.active DESC,b.name')->fetchAll();
$branches=is_admin()?$pdo->query('SELECT id,name,code FROM branches WHERE active=1 ORDER BY name')->fetchAll():[];
$title='Bank accounts';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h1 class="h3 fw-bold mb-1">Bank Accounts</h1><p class="text-secondary mb-0">Create, edit, enable and disable accounts — every bank transaction stays attached to its account.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#bank"><i class="bi bi-plus-lg"></i> Add bank account</button></div>
<div class="card p-3 p-lg-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Account</th><th>Bank</th><th>Account no.</th><th>Opening</th><th>In</th><th>Out</th><th>Balance</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($rows as $r):$balance=$r['opening_balance']+$r['money_in']-$r['money_out'];?><tr><td class="fw-bold"><?=e($r['name'])?><small class="d-block text-secondary"><?=e($r['branch_name'])?></small></td><td><?=e($r['bank_name'])?></td><td><?=e($r['account_number'])?></td><td><?=money($r['opening_balance'])?></td><td class="text-success"><?=money($r['money_in'])?></td><td class="text-danger"><?=money($r['money_out'])?></td><td class="fw-bold"><?=money($balance)?></td><td><span class="status <?=$r['active']?'status-paid':'status-cancelled'?>"><?=$r['active']?'Active':'Inactive'?></span></td><td class="text-nowrap"><button class="btn btn-sm btn-outline-secondary me-1" data-bs-toggle="modal" data-bs-target="#edit<?=$r['id']?>"><i class="bi bi-pencil"></i></button><form method="post" class="d-inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-secondary me-1" name="toggle"><?=$r['active']?'Disable':'Enable'?></button></form><form method="post" class="d-inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-danger" name="delete" data-confirm="Delete this bank account permanently?">Delete</button></form></td></tr>
<div class="modal fade" id="edit<?=$r['id']?>"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h2 class="h5 mb-0">Edit bank account</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$r['id']?>"><label class="form-label">Account name</label><input class="form-control mb-3" name="name" value="<?=e($r['name'])?>" required><label class="form-label">Bank name</label><input class="form-control mb-3" name="bank_name" value="<?=e($r['bank_name'])?>" required><label class="form-label">Account number</label><input class="form-control mb-3" name="account_number" value="<?=e($r['account_number'])?>" required><label class="form-label">Opening balance</label><input class="form-control mb-3" type="number" min="0" step=".01" name="opening_balance" value="<?=e($r['opening_balance'])?>"><?php if(is_admin()):?><label class="form-label">Branch</label><select class="form-select mb-3" name="branch_id"><?php foreach($branches as $b):?><option value="<?=$b['id']?>" <?= $r['branch_id']==$b['id']?'selected':''?>><?=e($b['name'].' ('.$b['code'].')')?></option><?php endforeach?></select><?php endif?><div class="form-check"><input class="form-check-input" type="checkbox" name="active" id="active<?=$r['id']?>" <?=$r['active']?'checked':''?>><label class="form-check-label" for="active<?=$r['id']?>">Account active</label></div></div><div class="modal-footer"><button class="btn btn-primary" name="update">Save changes</button></div></form></div></div>
<?php endforeach?></tbody></table></div></div>
<div class="modal fade" id="bank"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h2 class="h5 mb-0">Create bank account</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><label class="form-label">Account name</label><input class="form-control mb-3" name="name" placeholder="e.g. Main USD Account" required><label class="form-label">Bank name</label><input class="form-control mb-3" name="bank_name" required><label class="form-label">Account number</label><input class="form-control mb-3" name="account_number" required><label class="form-label">Opening balance</label><input class="form-control mb-3" type="number" min="0" step=".01" name="opening_balance" value="0"><?php if(is_admin()):?><label class="form-label">Branch</label><select class="form-select" name="branch_id"><?php foreach($branches as $b):?><option value="<?=$b['id']?>"><?=e($b['name'].' ('.$b['code'].')')?></option><?php endforeach?></select><?php endif?></div><div class="modal-footer"><button class="btn btn-primary" name="create">Save bank account</button></div></form></div></div>
<?php require __DIR__.'/partials/footer.php';?>
