<?php
require __DIR__.'/bootstrap.php';require_roles(['admin','accountant']);
$branch=is_admin()?null:require_branch();$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['from']??'')?$_GET['from']:'';$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['to']??'')?$_GET['to']:'';$accountFilter=(int)($_GET['account_id']??0);
$conditions=[];$params=[];if($branch!==null)$conditions[]='b.branch_id='.(int)$branch;if($accountFilter>0)$conditions[]='t.bank_account_id='.$accountFilter;if($to!==''){$conditions[]='t.transaction_date <= ?';$params[]=$to.' 23:59:59';}$where=$conditions?' WHERE '.implode(' AND ',$conditions):'';
// Include earlier entries when calculating balances; show only rows in the requested period.
$q=$pdo->prepare("SELECT t.*,b.name account_name,b.opening_balance,\n       p.reference_no payment_ref,p.id payment_id,\n       g.invoice_no general_inv_no,\n       s.awb ship_awb,(SELECT si.invoice_no FROM shipment_invoices si WHERE si.shipment_id=p.shipment_id ORDER BY si.id DESC LIMIT 1) ship_inv_no,\n       ie.payer income_payer,ie.description income_desc,\n       ex.description expense_desc\nFROM bank_transactions t\nJOIN bank_accounts b ON b.id=t.bank_account_id\nLEFT JOIN payments p ON p.id=IF(t.source_table='payments',t.source_id,NULL)\nLEFT JOIN general_invoices g ON g.id=p.general_invoice_id\nLEFT JOIN shipments s ON s.id=p.shipment_id\nLEFT JOIN income_entries ie ON ie.id=IF(t.source_table='income_entries',t.source_id,NULL)\nLEFT JOIN expenses ex ON ex.id=IF(t.source_table='expenses',t.source_id,NULL)".$where.' ORDER BY t.bank_account_id,t.transaction_date,t.id');$q->execute($params);$rows=$q->fetchAll();
$balances=[];$data=[];foreach($rows as $r){$id=(int)$r['bank_account_id'];if(!isset($balances[$id]))$balances[$id]=(float)$r['opening_balance'];$balances[$id]+=(float)$r['amount_in']-(float)$r['amount_out'];if($from===''||$r['transaction_date']>=$from.' 00:00:00'){$type=(string)$r['transaction_type'];if($type==='Payment')$ref=$r['ship_inv_no']?:$r['general_inv_no']?:($r['ship_awb']?'AWB '.$r['ship_awb']:('Payment #'.$r['source_id']));elseif($type==='Income')$ref=$r['income_payer']?:$r['income_desc']?:('Income #'.$r['source_id']);else$ref=$r['expense_desc']?:('Expense #'.$r['source_id']);$data[]=[date('d M Y',strtotime($r['transaction_date'])),substr($r['account_name'],0,17),$type,substr($ref,0,15),number_format((float)$r['amount_in'],2),number_format((float)$r['amount_out'],2),number_format($balances[$id],2)];}}
function pdf_text(string $text): string{return str_replace(['\\','(',')',"\r","\n"],['\\\\','\\(', '\\)',' ',' '],$text);}
function pdf_label(string &$stream,float $x,float $y,string $text,float $size=9,string $font='F1',string $color='0.10 0.16 0.24'): void {$stream.="BT /$font $size Tf $color rg $x $y Td (".pdf_text($text).") Tj ET\n";}
function pdf_company_logo(): ?array {$path=__DIR__.'/'.ltrim(setting('logo_path',''),'/');if(!is_file($path))return null;$info=@getimagesize($path);if(!$info)return null;$image=null;if($info[2]===IMAGETYPE_JPEG)$data=file_get_contents($path);elseif(function_exists('imagejpeg')){if($info[2]===IMAGETYPE_PNG)$image=@imagecreatefrompng($path);elseif($info[2]===IMAGETYPE_WEBP&&function_exists('imagecreatefromwebp'))$image=@imagecreatefromwebp($path);if(!$image)return null;ob_start();imagejpeg($image,null,90);$data=ob_get_clean();imagedestroy($image);}else return null;return $data?['data'=>$data,'width'=>$info[0],'height'=>$info[1]]:null;}
$logo=pdf_company_logo();$chunks=array_chunk($data?:[['','','','','','']],25);$objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',4=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'];$logoObject=$logo?5:0;if($logo)$objects[$logoObject]='<< /Type /XObject /Subtype /Image /Width '.$logo['width'].' /Height '.$logo['height'].' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '.strlen($logo['data'])." >>\nstream\n".$logo['data']."\nendstream";$pageStart=$logo?6:5;$kids=[];$company=setting('company_name','CargoSom');$tagline=setting('company_tagline','Cargo Agency');$address=setting('company_address','');$mobile=setting('company_mobile_numbers','');
foreach($chunks as $index=>$pageRows){$pageId=$pageStart+$index*2;$contentId=$pageId+1;$kids[]=$pageId.' 0 R';$stream="q\n0.05 0.20 0.35 rg 0 686 612 106 re f\nQ\n";if($logo){$ratio=$logo['width']/$logo['height'];$w=min(68,52*$ratio);$stream.="q\n$w 0 0 52 42 716 cm /Im1 Do\nQ\n";$companyX=122;}else{$stream.="q\n0.10 0.35 0.54 rg 42 716 62 52 re f\nQ\n";pdf_label($stream,57,738,strtoupper(substr($company,0,2)),'18','F2','1 1 1');$companyX=122;}pdf_label($stream,$companyX,758,$company,'18','F2','1 1 1');pdf_label($stream,$companyX,741,$tagline,'9','F1','0.82 0.91 0.97');if($address)pdf_label($stream,$companyX,726,substr($address,0,55),'8','F1','0.82 0.91 0.97');if($mobile)pdf_label($stream,$companyX,712,substr($mobile,0,45),'8','F1','0.82 0.91 0.97');pdf_label($stream,420,758,'Generated: '.date('d M Y'),'8','F1','1 1 1');pdf_label($stream,420,744,'Period: '.($from?:'All').' - '.($to?:'Today'),'8','F1','0.82 0.91 0.97');pdf_label($stream,420,728,'BANK TRANSACTIONS','10','F2','1 1 1');
    $headers=['Date','Account','Transaction','Reference','Money In','Money Out','Balance'];$xs=[42,100,205,272,342,417,492];$widths=[58,105,67,70,75,75,78];$stream.="q\n0.10 0.35 0.54 rg 42 652 528 24 re f\nQ\n";foreach($headers as $i=>$_)pdf_label($stream,$xs[$i]+4,661,$headers[$i],'7','F2','1 1 1');$y=631;
    foreach($pageRows as $rowIndex=>$row){if(!$data){pdf_label($stream,185,$y,'No bank transactions found for this date range.','10','F1','0.35 0.42 0.48');break;}if($rowIndex%2===0)$stream.="q\n0.95 0.97 0.99 rg 42 ".($y-8)." 528 21 re f\nQ\n";$stream.="q\n0.86 0.89 0.92 RG 0.4 w 42 ".($y-8)." m 570 ".($y-8)." l S\nQ\n";foreach($row as $i=>$cell){$color=$i===4?'0.05 0.50 0.27':($i===5?'0.76 0.20 0.20':($i===6?'0.08 0.28 0.52':'0.10 0.16 0.24'));pdf_label($stream,$xs[$i]+4,$y,substr($cell,0,$i===1?17:($i===3?15:12)),'7',$i===6?'F2':'F1',$color);}$y-=21;}
    $stream.="q\n0.86 0.89 0.92 RG 0.5 w 42 120 m 570 120 l S\nQ\n";pdf_label($stream,42,102,'Opening balance + money in - money out','8','F1','0.38 0.44 0.50');pdf_label($stream,500,102,'Page '.($index+1).' of '.count($chunks),'8','F1','0.38 0.44 0.50');$objects[$contentId]='<< /Length '.strlen($stream)." >>\nstream\n".$stream."endstream";$resources='<< /Font << /F1 3 0 R /F2 4 0 R >>'.($logo?' /XObject << /Im1 '.$logoObject.' 0 R >>':'').' >>';$objects[$pageId]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources '.$resources.' /Contents '.$contentId.' 0 R >>';}
$objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($objects);$pdf="%PDF-1.4\n";$offsets=[0];foreach($objects as $id=>$object){$offsets[$id]=strlen($pdf);$pdf.=$id." 0 obj\n".$object."\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ', $offsets[$i]??0)."\n";$pdf.="trailer << /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n".$xref."\n%%EOF";
while(ob_get_level())ob_end_clean();header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="bank-transactions-'.date('Y-m-d').'.pdf"');header('Content-Length: '.strlen($pdf));echo $pdf;
