<?php
require __DIR__.'/bootstrap.php';
require_login();
$me=user();
$where=is_admin()?'':' WHERE (s.branch_id='.(int)require_branch().' OR s.to_branch_id='.(int)require_branch().')';
if($me['role']==='customer') $where.=is_admin()?' WHERE s.customer_id='.(int)$me['id']:' AND s.customer_id='.(int)$me['id'];
$stats=$pdo->query("SELECT COUNT(*) total,COALESCE(SUM(pcs),0) pcs,COALESCE(SUM(kg),0) kg,COALESCE(SUM(balance_mgq),0) balance,SUM(status='In Transit') transit FROM shipments s$where")->fetch();
$finance=['income'=>0,'expenses'=>0,'invoices'=>0];
if(in_array($me['role'],['super_admin','admin','accountant'],true)){
    $scope=is_admin()?'':' WHERE branch_id='.(int)require_branch();
    $paymentScope=is_admin()?'':' JOIN shipments s ON s.id=p.shipment_id WHERE s.branch_id='.(int)require_branch();
    $finance['income']=(float)$pdo->query("SELECT COALESCE(SUM(p.amount),0) FROM payments p$paymentScope")->fetchColumn();
    $finance['expenses']=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM expenses$scope")->fetchColumn();
    $finance['invoices']=(float)$pdo->query("SELECT COALESCE(SUM(i.total),0) FROM shipment_invoices i JOIN shipments s ON s.id=i.shipment_id".(is_admin()?" WHERE i.status<>'Cancelled'":" WHERE i.status<>'Cancelled' AND s.branch_id=".(int)require_branch()))->fetchColumn();
}
$recent=$pdo->query("SELECT s.*,a.code airline FROM shipments s JOIN airlines a ON a.id=s.airline_id $where ORDER BY s.shipment_date DESC,s.id DESC LIMIT 7")->fetchAll();
$title='Dashboard';require __DIR__.'/partials/header.php';
?>
<section class="hero mb-4"><div class="row align-items-center"><div class="col-lg-8"><div class="text-uppercase small opacity-75 mb-2"><?=e(app_date())?></div><h1 class="h2 fw-bold">Cargo operations at a glance</h1><p class="mb-0 opacity-75"><?php if(is_admin()):?>All branch operations<?php else:?>Only <?=e($me['branch_name']??'your assigned branch')?> data is shown here<?php endif?>.</p></div><div class="col-lg-4 text-lg-end mt-3 mt-lg-0"><span class="badge text-bg-light text-dark me-2"><?=is_admin()?'All branches':e($me['branch_name']??'Your branch')?></span><a class="btn btn-light fw-semibold" href="cargo.php">View shipment register</a></div></div></section>
<div class="row g-3 mb-4"><?php foreach([['bi-box-seam','Shipments',$stats['total']],['bi-collection','Pieces',$stats['pcs']],['bi-speedometer2','Total KG',number_format((float)$stats['kg'],2)],['bi-airplane','In Transit',$stats['transit']]] as [$icon,$label,$value]):?><div class="col-6 col-lg-3"><div class="card metric p-3 h-100"><div class="d-flex justify-content-between"><div><div class="text-secondary small"><?=e($label)?></div><div class="value"><?=e($value??0)?></div></div><i class="bi <?=e($icon)?>"></i></div></div></div><?php endforeach?></div>
<?php if(in_array($me['role'],['super_admin','admin','accountant'],true)):?><div class="row g-3 mb-4"><div class="col-md-3"><div class="card p-4 h-100"><small class="text-secondary">Payment income</small><strong class="h5 text-success"><?=money($finance['income'])?></strong><a class="small" href="income.php">View income</a></div></div><div class="col-md-3"><div class="card p-4 h-100"><small class="text-secondary">Expenses</small><strong class="h5 text-danger"><?=money($finance['expenses'])?></strong><a class="small" href="expenses.php">View expenses</a></div></div><div class="col-md-3"><div class="card p-4 h-100"><small class="text-secondary">Invoiced</small><strong class="h5"><?=money($finance['invoices'])?></strong><a class="small" href="shipment_invoices.php">View invoices</a></div></div><div class="col-md-3"><div class="card p-4 h-100 border-start border-danger border-4"><small class="text-secondary">Outstanding MGQ</small><strong class="h5 text-danger"><?=money($stats['balance'])?></strong><a class="small" href="invoices.php">Collect payments</a></div></div></div><?php endif?>
<div class="card p-3 p-lg-4"><div class="d-flex justify-content-between mb-3"><h2 class="h5">Latest shipments</h2><a href="cargo.php" class="btn btn-sm btn-outline-primary">Search all</a></div><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>AWB</th><th>Sender</th><th>Airline</th><th>KG</th><th>Total</th><th>Balance MGQ</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=date('d M',strtotime($r['shipment_date']))?></td><td class="fw-semibold"><?=e($r['awb'])?></td><td><?=e($r['sender'])?></td><td><?=e($r['airline'])?></td><td><?=e($r['kg'])?></td><td><?=money($r['total'])?></td><td class="fw-bold <?=$r['balance_mgq']>0?'text-danger':'text-success'?>"><?=money($r['balance_mgq'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach?></tbody></table></div></div>
<?php require __DIR__.'/partials/footer.php';?>
