<?php
require __DIR__.'/bootstrap.php';require_perm('income.manage');$me=user();
$branch=is_admin()?null:require_branch();$where=$branch===null?'':' WHERE i.branch_id='.(int)$branch;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
if(isset($_POST['delete'])){$id=(int)$_POST['id'];$pdo->beginTransaction();try{$pdo->prepare("DELETE FROM bank_transactions WHERE source_table='income_entries' AND source_id=?")->execute([$id]);$d=$pdo->prepare('DELETE FROM income_entries WHERE id=?'.($branch===null?'':' AND branch_id='.(int)$branch));$d->execute([$id]);$pdo->commit();flash('success','Income entry deleted.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger','Income entry could not be deleted.');}redirect('income.php');}
if(isset($_POST['update'])){$id=(int)$_POST['id'];$bankId=(int)($_POST['bank_account_id']??0);if($bankId){$eb=$pdo->prepare('SELECT branch_id FROM income_entries WHERE id=?');$eb->execute([$id]);if(!bank_account_id_for_branch($bankId,(int)$eb->fetchColumn())){flash('danger','Select an active bank account for this branch.');redirect('income.php');}}$u=$pdo->prepare('UPDATE income_entries SET income_date=?,category=?,amount=?,shipment_id=?,payer=?,payment_method=?,reference_no=?,description=?,bank_account_id=? WHERE id=?'.($branch===null?'':' AND branch_id='.(int)$branch));$u->execute([$_POST['income_date'],$_POST['category'],$_POST['amount'],$_POST['shipment_id']?:null,trim($_POST['payer']),$_POST['payment_method'],trim($_POST['reference_no']),trim($_POST['description']),$bankId?:null,$id]);sync_income_bank_transaction($id,$bankId,(float)$_POST['amount'],$_POST['income_date']);flash('success','Income entry updated.');redirect('income.php');}
$incomeBranch=$branch??(int)$_POST['branch_id'];$bankId=(int)($_POST['bank_account_id']??0);if($bankId&&!bank_account_id_for_branch($bankId,$incomeBranch)){flash('danger','Select an active bank account for this branch.');redirect('income.php');}try{$pdo->beginTransaction();$pdo->prepare('INSERT INTO income_entries(income_date,category,amount,shipment_id,bank_account_id,branch_id,payer,payment_method,reference_no,description,recorded_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$_POST['income_date'],$_POST['category'],$_POST['amount'],$_POST['shipment_id']?:null,$bankId?:null,$incomeBranch,trim($_POST['payer']),$_POST['payment_method'],trim($_POST['reference_no']),trim($_POST['description']),$me['id']]);$eid=(int)$pdo->lastInsertId();if($bankId)add_bank_transaction($bankId,'Income','income_entries',$eid,(float)$_POST['amount'],$_POST['income_date'].' '.date('H:i:s'));$pdo->commit();flash('success','Income entry recorded.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger','Income entry could not be recorded.');}redirect('income.php');}
$manual=$pdo->query('SELECT i.*,s.awb,b.name bank_account_name FROM income_entries i LEFT JOIN shipments s ON s.id=i.shipment_id LEFT JOIN bank_accounts b ON b.id=i.bank_account_id'.$where.' ORDER BY i.income_date DESC,i.id DESC')->fetchAll();$banks=$pdo->query('SELECT id,name,bank_name,account_number,branch_id FROM bank_accounts WHERE active=1'.($branch===null?'':' AND branch_id='.(int)$branch).' ORDER BY name')->fetchAll();
$paymentWhere=$branch===null?'':' WHERE s.branch_id='.(int)$branch;
$payments=$pdo->query('SELECT p.id,DATE(p.paid_at) income_date,p.amount,p.payment_method,p.reference_no,p.location,s.awb,s.id shipment_id FROM payments p JOIN shipments s ON s.id=p.shipment_id'.$paymentWhere.' ORDER BY p.paid_at DESC')->fetchAll();
$monthPayments=(float)$pdo->query("SELECT COALESCE(SUM(p.amount),0) FROM payments p JOIN shipments s ON s.id=p.shipment_id".($branch===null?" WHERE p.paid_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01')":" WHERE s.branch_id=".(int)$branch." AND p.paid_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01')"))->fetchColumn();
$monthManual=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM income_entries".($branch===null?" WHERE income_date>=DATE_FORMAT(CURDATE(),'%Y-%m-01')":" WHERE branch_id=".(int)$branch." AND income_date>=DATE_FORMAT(CURDATE(),'%Y-%m-01')"))->fetchColumn();
$shipments=$pdo->query("SELECT id,awb FROM shipments WHERE status<>'Cancelled'".($branch===null?'':' AND branch_id='.(int)$branch).' ORDER BY shipment_date DESC')->fetchAll();$title='Income';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h1 class="h3 fw-bold mb-1">Income</h1><p class="text-secondary mb-0"><?=is_admin()?'All branches':'Your branch only'?> · shipment payments and agency revenue.</p></div><div class="no-print"><button class="btn btn-outline-primary" onclick="window.print()"><i class="bi bi-printer"></i> Print</button> <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#income"><i class="bi bi-plus-lg"></i> Add income</button></div></div>
<div class="print-area"><div class="row g-3 mb-4"><?php foreach([['Shipment payments',$monthPayments],['Other income',$monthManual],['Total income',$monthPayments+$monthManual]] as [$label,$amount]):?><div class="col-md-4"><div class="card p-4"><small class="text-secondary"><?=e($label)?> this month</small><strong class="h4 text-success"><?=money($amount)?></strong></div></div><?php endforeach?></div>
<div class="card p-3 p-lg-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h5 mb-0">Shipment payment income</h2><input class="form-control no-print" style="width:230px;max-width:230px" data-search-for="#paymentsIncomeTable" placeholder="Search payments…"></div><div class="table-responsive"><table class="table" id="paymentsIncomeTable"><thead><tr><th>Date</th><th>AWB</th><th>Location</th><th>Method</th><th>Reference</th><th>Amount</th><th></th></tr></thead><tbody><?php foreach($payments as $r):?><tr><td><?=app_date($r['income_date'])?></td><td><?=e($r['awb'])?></td><td><?=e($r['location'])?></td><td><?=e($r['payment_method'])?></td><td><?=e($r['reference_no']?:'-')?></td><td class="fw-bold text-success"><?=money($r['amount'])?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="shipment_view.php?id=<?=$r['shipment_id']?>"><i class="bi bi-eye"></i> View</a> <a class="btn btn-sm btn-outline-secondary" href="invoice_print.php?shipment_id=<?=$r['shipment_id']?>" target="_blank"><i class="bi bi-receipt"></i> Invoice</a></td></tr><?php endforeach?></tbody></table></div></div>
<div class="card p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h5 mb-0">Other income</h2><input class="form-control no-print" style="width:230px;max-width:230px" data-search-for="#otherIncomeTable" placeholder="Search income…"></div><div class="table-responsive"><table class="table" id="otherIncomeTable"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Payer</th><th>AWB</th><th>Bank Account</th><th>Amount</th><th></th></tr></thead><tbody><?php foreach($manual as $r):?><tr><td><?=app_date($r['income_date'])?></td><td><?=e($r['category'])?></td><td><?=e($r['description'])?></td><td><?=e($r['payer']?:'-')?></td><td><?=e($r['awb']?:'-')?></td><td><?=e($r['bank_account_name']?:'Cash / not linked')?></td><td class="fw-bold text-success"><?=money($r['amount'])?></td><td class="text-nowrap"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#incomeView" data-income="<?=e(json_encode($r))?>"><i class="bi bi-eye"></i> View</button> <button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#incomeEdit" data-income="<?=e(json_encode($r))?>"><i class="bi bi-pencil"></i> Edit</button> <form method="post" class="d-inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-danger" name="delete" data-confirm="Delete this income entry?"><i class="bi bi-trash"></i> Delete</button></form></td></tr><?php endforeach?></tbody></table></div></div>
</div>
<style>@media print{body *{visibility:hidden}.print-area,.print-area *{visibility:visible}.print-area{position:absolute;left:0;top:0;width:100%}.no-print{display:none!important}}</style>
<script>(function(){document.querySelectorAll('[data-search-for]').forEach(inp=>{const table=document.querySelector(inp.dataset.searchFor);if(!table)return;inp.addEventListener('input',()=>{const q=inp.value.trim().toLowerCase();table.querySelectorAll('tbody tr').forEach(r=>r.hidden=q!==''&&!r.innerText.toLowerCase().includes(q))})})})();</script>
<div class="modal fade" id="income"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h2 class="h5">Add income</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><?php if(is_admin()):?><input type="hidden" name="branch_id" value="<?=$me['branch_id']?>"><?php endif?><label class="form-label">Date</label><input class="form-control mb-3" type="date" name="income_date" value="<?=date('Y-m-d')?>" required><label class="form-label">Category</label><select class="form-select mb-3" name="category"><?php foreach(['Cargo Service','Delivery','Storage','Handling','Commission','Other'] as $x):?><option><?=$x?></option><?php endforeach?></select><label class="form-label">Amount</label><input class="form-control mb-3" type="number" min=".01" step=".01" name="amount" required><label class="form-label">Shipment (optional)</label><select class="form-select mb-3" name="shipment_id"><option value="">General income</option><?php foreach($shipments as $s):?><option value="<?=$s['id']?>"><?=e($s['awb'])?></option><?php endforeach?></select><label class="form-label">Payer</label><input class="form-control mb-3" name="payer"><label class="form-label">Payment method</label><select class="form-select mb-3" name="payment_method"><?php foreach(['Cash','Bank Transfer','Mobile Money','Card','Other'] as $x):?><option><?=$x?></option><?php endforeach?></select><label class="form-label">Bank account <small class="text-secondary">(optional)</small></label><select class="form-select mb-3" name="bank_account_id"><option value="">Cash / not linked to a bank</option><?php foreach($banks as $b):?><option value="<?=$b['id']?>"><?=e($b['name'].' · '.$b['bank_name'].' · '.$b['account_number'])?></option><?php endforeach?></select><label class="form-label">Reference</label><input class="form-control mb-3" name="reference_no"><label class="form-label">Description</label><input class="form-control" name="description" required></div><div class="modal-footer"><button class="btn btn-primary">Save income</button></div></form></div></div>
<div class="modal fade" id="incomeView"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h2 class="h5">Income entry</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body" id="incomeViewBody"></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Close</button></div></div></div></div>
<div class="modal fade" id="incomeEdit"><div class="modal-dialog"><form method="post" class="modal-content" id="incomeEditForm"><div class="modal-header"><h2 class="h5">Edit income</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id"><label class="form-label">Date</label><input class="form-control mb-3" type="date" name="income_date" required><label class="form-label">Category</label><select class="form-select mb-3" name="category"><?php foreach(['Cargo Service','Delivery','Storage','Handling','Commission','Other'] as $x):?><option><?=$x?></option><?php endforeach?></select><label class="form-label">Amount</label><input class="form-control mb-3" type="number" min=".01" step=".01" name="amount" required><label class="form-label">Shipment (optional)</label><select class="form-select mb-3" name="shipment_id"><option value="">General income</option><?php foreach($shipments as $s):?><option value="<?=$s['id']?>"><?=e($s['awb'])?></option><?php endforeach?></select><label class="form-label">Payer</label><input class="form-control mb-3" name="payer"><label class="form-label">Payment method</label><select class="form-select mb-3" name="payment_method"><?php foreach(['Cash','Bank Transfer','Mobile Money','Card','Other'] as $x):?><option><?=$x?></option><?php endforeach?></select><label class="form-label">Bank account <small class="text-secondary">(optional)</small></label><select class="form-select mb-3" name="bank_account_id"><option value="">Cash / not linked to a bank</option><?php foreach($banks as $b):?><option value="<?=$b['id']?>"><?=e($b['name'].' · '.$b['bank_name'].' · '.$b['account_number'])?></option><?php endforeach?></select><label class="form-label">Reference</label><input class="form-control mb-3" name="reference_no"><label class="form-label">Description</label><input class="form-control" name="description" required></div><div class="modal-footer"><button class="btn btn-primary" name="update">Save changes</button></div></form></div></div>
<script>
(function(){
  const parse=(el)=>{try{return JSON.parse(el.dataset.income||'{}')}catch(e){return{}}};
  document.querySelectorAll('[data-bs-target="#incomeEdit"]').forEach(b=>b.addEventListener('click',()=>{
    const d=parse(b),f=document.querySelector('#incomeEditForm');
    const set=(n,v)=>{const el=f.querySelector('[name="'+n+'"]');if(el)el.value=(v===null||v===undefined)?'':v;};
    f.querySelector('[name="id"]').value=d.id||'';
    set('income_date',d.income_date);set('category',d.category);set('amount',d.amount);
    set('shipment_id',d.shipment_id||'');set('bank_account_id',d.bank_account_id||'');set('payer',d.payer);set('payment_method',d.payment_method);
    set('reference_no',d.reference_no);set('description',d.description);
  }));
  document.querySelectorAll('[data-bs-target="#incomeView"]').forEach(b=>b.addEventListener('click',()=>{
    const d=parse(b),box=document.querySelector('#incomeViewBody');
    const row=(k,v)=>{const x=v===null||v===''?'—':v;return '<div class="d-flex justify-content-between mb-1"><span class="text-secondary">'+k+'</span><strong>'+x+'</strong></div>';};
    let h='<div class="mb-2"><span class="badge text-bg-primary">#'+(d.id||'')+'</span>'+(d.awb?' <span class="badge text-bg-light border">AWB: '+d.awb+'</span>':'')+'</div>';
    h+=row('Date',d.income_date)+row('Category',d.category)+row('Amount',d.amount)+row('Bank account',d.bank_account_name||d.bank_account_id||'—')+row('Payer',d.payer)+row('Payment method',d.payment_method)+row('Reference',d.reference_no)+row('Description',d.description);
    box.innerHTML=h;
  }));
})();
</script>
<?php require __DIR__.'/partials/footer.php';?>
