<?php
require __DIR__.'/bootstrap.php';
require_perm('payments.view');
$rows=$pdo->query('SELECT i.id AS invoice_id,i.invoice_no,i.total,i.status,s.awb,s.extra,p.amount,p.location,p.payment_method,p.reference_no,p.paid_at,u.name received_by FROM shipment_invoices i JOIN shipments s ON s.id=i.shipment_id LEFT JOIN payments p ON p.shipment_id=s.id LEFT JOIN users u ON u.id=p.received_by ORDER BY p.paid_at DESC,i.id DESC')->fetchAll();
$title='Invoice payment history';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h1 class="h3 fw-bold mb-1">Invoice payment history</h1><p class="text-secondary mb-0">Payments received against shipment invoices.</p></div><a class="btn btn-outline-primary" href="shipment_invoices.php">Back to invoices</a></div>
<div class="card p-3 p-lg-4"><input class="form-control mb-3" style="max-width:420px" data-table-search placeholder="Search invoice, AWB, or payment reference"><div class="table-responsive"><table class="table"><thead><tr><th>Invoice</th><th>AWB</th><th>Paid date</th><th>Method / reference</th><th>Received by</th><th class="text-end">Amount</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="fw-bold"><a class="text-decoration-none" href="invoice_print.php?id=<?=$r['invoice_id']?>" target="_blank"><?=e($r['invoice_no'])?></a><small class="d-block text-secondary">Total <?=money((float)$r['total']+(float)$r['extra'])?> · Extra <?=money($r['extra'])?></small></td><td><?=e($r['awb'])?></td><td><?=e($r['paid_at']?date('d M Y H:i',strtotime($r['paid_at'])):'No payment')?></td><td><?=e($r['payment_method']?:'—')?><small class="d-block text-secondary"><?=e($r['reference_no']?:$r['location']?:'—')?></small></td><td><?=e($r['received_by']?:'—')?></td><td class="text-end fw-bold text-success"><?=e($r['amount']?money($r['amount']):'—')?></td><td><span class="status status-<?=strtolower(str_replace(' ','-',$r['status']))?>"><?=e($r['status'])?></span></td></tr><?php endforeach?></tbody></table></div></div>
<?php require __DIR__.'/partials/footer.php'; ?>
