<?php
require __DIR__.'/bootstrap.php';require_perm('payments.view');$me=user();
$b=(int)require_branch();$scope=is_admin()?'':' AND (branch_id='.$b.' OR to_branch_id='.$b.')';$sScope=is_admin()?'':' AND (s.branch_id='.$b.' OR s.to_branch_id='.$b.')';$wScope=is_admin()?'':' WHERE (s.branch_id='.$b.' OR s.to_branch_id='.$b.')';$gScope=is_admin()?'':' WHERE g.branch_id='.$b;
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();require_perm('payments.record');
    if(isset($_POST['edit_payment'])){
        $paymentId=(int)$_POST['payment_id'];$amount=(float)$_POST['amount'];
        $ep=$pdo->prepare('SELECT p.*,s.total,s.extra,s.paid_dxb,s.balance_mgq,s.branch_id,s.to_branch_id,g.branch_id gbranch_id FROM payments p LEFT JOIN shipments s ON s.id=p.shipment_id LEFT JOIN general_invoices g ON g.id=p.general_invoice_id WHERE p.id=?'.(is_admin()?'':' AND (s.branch_id='.$b.' OR s.to_branch_id='.$b.' OR g.branch_id='.$b.')'));
        $ep->execute([$paymentId]);$pay=$ep->fetch();
        if(!$pay||$amount<=0){flash('danger','Payment not found or amount invalid.');redirect('invoices.php');}
        $payLocation=$_POST['location']??$pay['location'];$method=$_POST['method']??$pay['payment_method'];
        if($pay['shipment_id']&&$amount>$pay['amount']+max(0,(float)$pay['balance_mgq'])){flash('danger','Amount cannot exceed the shipment balance.');redirect('invoices.php');}
        $payBranch=(int)($pay['shipment_id']?((int)$pay['to_branch_id']>0&&$payLocation==='MGQ'?(int)$pay['to_branch_id']:(int)$pay['branch_id']):(int)($pay['gbranch_id']??0));
        $bankId=0;if($method==='Bank Transfer'||(int)($_POST['bank_account_id']??0)>0){$bankId=bank_account_id_for_branch((int)($_POST['bank_account_id']??0),$payBranch);if(!$bankId){flash('danger','Select an active bank account for the '.e($payLocation==='MGQ'?'destination':'origin').' branch.');redirect('invoices.php');}}
        $paidAt=$pay['paid_at'];if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$_POST['paid_at']??''))$paidAt=$_POST['paid_at'].' '.date('H:i:s',strtotime($paidAt));
        $pdo->beginTransaction();try{
            $pdo->prepare('UPDATE payments SET amount=?,location=?,payment_method=?,bank_account_id=?,reference_no=?,notes=?,paid_at=? WHERE id=?')->execute([$amount,$payLocation,$method,$bankId?:null,trim($_POST['reference']??''),trim($_POST['notes']??''),$paidAt,$paymentId]);
            if($bankId||$pay['bank_account_id'])sync_payment_bank_transaction($paymentId,$bankId,$amount,$paidAt);
            if($pay['shipment_id']){$newPaid=(float)$pay['paid_dxb']-$pay['amount']+$amount;$status=$newPaid>=((float)$pay['total']+(float)$pay['extra'])?'Paid':($newPaid<=0.004?'Unpaid':'Partially Paid');$pdo->prepare('UPDATE shipments SET paid_dxb=?,payment_receive=? WHERE id=?')->execute([$newPaid,$status,(int)$pay['shipment_id']]);}
            $pdo->commit();flash('success','Payment updated — bank transaction kept in sync.');
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger','Payment could not be updated.');}
        redirect('invoices.php');
    }
    if(isset($_POST['delete_payment'])){
        $paymentId=(int)$_POST['payment_id'];
        $dp=$pdo->prepare('SELECT p.id,p.amount,p.shipment_id,s.total,s.extra,s.paid_dxb,s.branch_id,s.to_branch_id,g.branch_id gbranch_id FROM payments p LEFT JOIN shipments s ON s.id=p.shipment_id LEFT JOIN general_invoices g ON g.id=p.general_invoice_id WHERE p.id=?'.(is_admin()?'':' AND (s.branch_id='.$b.' OR s.to_branch_id='.$b.' OR g.branch_id='.$b.')'));
        $dp->execute([$paymentId]);$pay=$dp->fetch();
        if(!$pay){flash('danger','Payment not found.');redirect('invoices.php');}
        $pdo->beginTransaction();try{
            $pdo->prepare("DELETE FROM bank_transactions WHERE source_table='payments' AND source_id=?")->execute([$paymentId]);
            if($pay['shipment_id']){$newPaid=(float)$pay['paid_dxb']-$pay['amount'];$status=$newPaid>=((float)$pay['total']+(float)$pay['extra'])?'Paid':($newPaid<=0.004?'Unpaid':'Partially Paid');$pdo->prepare('UPDATE shipments SET paid_dxb=?,payment_receive=? WHERE id=?')->execute([$newPaid,$status,(int)$pay['shipment_id']]);}
            $pdo->prepare('DELETE FROM payments WHERE id=?')->execute([$paymentId]);
            $pdo->commit();flash('success','Payment deleted — bank statement and balance updated.');
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger','Payment could not be deleted.');}
        redirect('invoices.php');
    }
    $id=(int)$_POST['shipment_id'];$amount=(float)$_POST['amount'];
    $s=$pdo->prepare('SELECT total,extra,paid_dxb,balance_mgq,branch_id,to_branch_id FROM shipments WHERE id=?'.$scope);$s->execute([$id]);$ship=$s->fetch();
    $extra=(float)($_POST['extra']??$ship['extra']??0);$payLocation=$_POST['location']??'DXB';$remaining=$ship?max(0,(float)$ship['total']+(float)$extra-(float)$ship['paid_dxb']):0;
    if(!$ship||$amount<=0||$amount>$remaining){flash('danger','Payment must be greater than zero and cannot exceed the shipment balance.');redirect('invoices.php');}
    $payBranch=(int)$ship['branch_id'];if($payLocation==='MGQ'&&(int)($ship['to_branch_id']??0)>0)$payBranch=(int)$ship['to_branch_id'];
    $method=$_POST['method']??'Cash';$bankId=0;
    if($method==='Bank Transfer'||(int)($_POST['bank_account_id']??0)>0){$bankId=bank_account_id_for_branch((int)($_POST['bank_account_id']??0),$payBranch);if(!$bankId){flash('danger','Select an active bank account for the '.e($payLocation==='MGQ'?'destination':'origin').' branch.');redirect('invoices.php');}}
    $pdo->beginTransaction();try{$pdo->prepare('INSERT INTO payments(shipment_id,bank_account_id,amount,location,payment_method,reference_no,notes,received_by,paid_at) VALUES(?,?,?,?,?,?,?,?,NOW())')->execute([$id,$bankId?:null,$amount,$_POST['location'],$method,trim($_POST['reference']),trim($_POST['notes']),$me['id']]);$paymentId=(int)$pdo->lastInsertId();if($bankId)add_bank_transaction($bankId,'Payment','payments',$paymentId,$amount,date('Y-m-d H:i:s'));$newPaid=(float)$ship['paid_dxb']+$amount;$status=$newPaid>=((float)$ship['total']+(float)$extra)?'Paid':'Partially Paid';$pdo->prepare('UPDATE shipments SET paid_dxb=?,payment_receive=?,extra=? WHERE id=?'.$scope)->execute([$newPaid,$status,$extra,$id]);$pdo->commit();flash('success','Payment recorded and balance updated.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger','Payment could not be recorded.');}
    redirect('invoices.php');
}
$open=$pdo->query("SELECT s.*,a.code airline FROM shipments s JOIN airlines a ON a.id=s.airline_id WHERE s.balance_mgq>0 AND s.status<>'Cancelled'".$sScope.' ORDER BY s.shipment_date DESC')->fetchAll();
$bankAccounts=$pdo->query('SELECT a.id,a.name,a.bank_name,a.account_number,a.branch_id,br.name branch_name FROM bank_accounts a JOIN branches br ON br.id=a.branch_id WHERE a.active=1'.(is_admin()?'':' AND a.branch_id='.(int)require_branch()).' ORDER BY a.name')->fetchAll();
$payments=$pdo->query("SELECT p.*,s.awb AS payment_for,'Shipment' AS payment_type,u.name received_by_name,b.name bank_account_name,s.branch_id pay_branch_id,s.to_branch_id pay_to_branch_id,g.branch_id pay_ginv_branch_id,s.balance_mgq pay_balance_mgq FROM payments p JOIN shipments s ON s.id=p.shipment_id JOIN users u ON u.id=p.received_by LEFT JOIN bank_accounts b ON b.id=p.bank_account_id LEFT JOIN general_invoices g ON g.id=p.general_invoice_id".$wScope." UNION ALL SELECT p.*,g.invoice_no AS payment_for,'General invoice' AS payment_type,u.name received_by_name,b.name bank_account_name,s.branch_id pay_branch_id,s.to_branch_id pay_to_branch_id,g.branch_id pay_ginv_branch_id,s.balance_mgq pay_balance_mgq FROM payments p JOIN general_invoices g ON g.id=p.general_invoice_id JOIN users u ON u.id=p.received_by LEFT JOIN bank_accounts b ON b.id=p.bank_account_id LEFT JOIN shipments s ON s.id=p.shipment_id".$gScope.' ORDER BY paid_at DESC LIMIT 100')->fetchAll();
$totalOutstanding=(float)$pdo->query("SELECT COALESCE(SUM(balance_mgq),0) FROM shipments WHERE status<>'Cancelled'".$scope)->fetchColumn();$title='Payments';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h1 class="h3 fw-bold mb-1">Payment tracking</h1><p class="text-secondary mb-0"><?=is_admin()?'All branches':'Your branch only'?> · DXB payments and MGQ balances.</p></div><div class="card px-4 py-2"><small class="text-secondary">Outstanding MGQ</small><strong class="text-danger"><?=money($totalOutstanding)?></strong></div></div>
<div class="card p-3 p-lg-4 mb-4"><h2 class="h5 mb-3">Outstanding shipments</h2><div class="table-responsive"><table class="table"><thead><tr><th>AWB</th><th>Cargo</th><th>Extra</th><th>Invoice total</th><th>Paid DXB</th><th>Balance MGQ</th><th></th></tr></thead><tbody><?php foreach($open as $r):?><tr><td class="fw-semibold"><?=e($r['awb'])?><small class="d-block text-secondary"><?=e($r['airline'])?></small></td><td><?=money($r['total'])?></td><td><?=money($r['extra'])?></td><td class="fw-bold"><?=money((float)$r['total']+(float)$r['extra'])?></td><td class="text-success"><?=money($r['paid_dxb'])?></td><td class="fw-bold text-danger"><?=money($r['balance_mgq'])?></td><td><?php if(can('payments.record')):?><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#pay<?=$r['id']?>">Record payment</button><?php endif?></td></tr><?php endforeach?></tbody></table></div></div>
<div class="card p-3 p-lg-4"><h2 class="h5 mb-3">Payment history</h2><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Invoice / AWB</th><th>Location</th><th>Method / Bank account</th><th>Reference</th><th>Received by</th><th>Amount</th><th></th></tr></thead><tbody><?php foreach($payments as $p):?><tr><td><?=date('d M Y H:i',strtotime($p['paid_at']))?></td><td><?=e($p['payment_type'])?></td><td><?=e($p['payment_for'])?></td><td><?=e($p['location'])?></td><td><?=e($p['payment_method'])?><?php if($p['bank_account_name']):?><small class="d-block text-secondary"><?=e($p['bank_account_name'])?></small><?php endif?></td><td><?=e($p['reference_no']?:'—')?></td><td><?=e($p['received_by_name'])?></td><td class="fw-bold text-success"><?=money($p['amount'])?></td><td class="text-nowrap text-end"><?php if(can('payments.record')):?><button class="btn btn-sm btn-outline-secondary me-1" data-bs-toggle="modal" data-bs-target="#editPay<?=$p['id']?>"><i class="bi bi-pencil"></i> Edit</button><form method="post" class="d-inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="payment_id" value="<?=$p['id']?>"><button class="btn btn-sm btn-outline-danger" name="delete_payment" data-confirm="Delete this payment? The shipment balance and bank statement will be updated.">Delete</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></div>
<?php foreach($open as $r):?><div class="modal fade" id="pay<?=$r['id']?>"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h2 class="h5">Payment · <?=e($r['awb'])?></h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="shipment_id" value="<?=$r['id']?>"><div class="alert alert-light border small mb-3">Invoice total (USD): <strong><?=money((float)$r['total']+(float)$r['extra'])?></strong> · Current max due: <strong id="payMax<?=$r['id']?>"><?=money($r['balance_mgq'])?></strong></div><label class="form-label">Invoice Extra (USD)</label><input data-maxid="payMax<?=$r['id']?>" class="form-control mb-3 pay-extra" type="number" min="0" step=".01" name="extra" value="<?=e($r['extra'])?>" data-total="<?=$r['total']?>" data-paid="<?=$r['paid_dxb']?>"><label class="form-label">Amount (max USD)</label><input class="form-control mb-3 pay-amount" type="number" step=".01" min=".01" max="<?=$r['balance_mgq']?>" name="amount" required><label class="form-label">Payment location</label><select class="form-select mb-3" name="location"><option>DXB</option><option>MGQ</option></select><label class="form-label">Method</label><select class="form-select mb-3" name="method"><option>Cash</option><option>Bank Transfer</option><option>Mobile Money</option><option>Card</option><option>Other</option></select><label class="form-label">Deposit to bank account <small class="text-secondary">(required for Bank Transfer · optional for other methods — adds this payment to the bank statement)</small></label><select class="form-select mb-3" name="bank_account_id"><option value="">Select bank account</option><?php foreach($bankAccounts as $b):if(is_admin()||(int)$b['branch_id']===(int)$r['branch_id']||(int)$b['branch_id']===(int)($r['to_branch_id']??0)):?><option value="<?=$b['id']?>"><?=e($b['name'].' · '.$b['bank_name'].' · '.$b['account_number'].(!empty($b['branch_name'])?' ('.$b['branch_name'].')':''))?></option><?php endif;endforeach?></select><label class="form-label">Reference</label><input class="form-control mb-3" name="reference"><label class="form-label">Notes</label><input class="form-control" name="notes"></div><div class="modal-footer"><button class="btn btn-primary">Save payment</button></div></form></div></div><?php endforeach?>
<?php if(can('payments.record')):foreach($payments as $p):$bankBranches=$p['pay_ginv_branch_id']?[(int)$p['pay_ginv_branch_id']]:[(int)$p['pay_branch_id'],(int)$p['pay_to_branch_id']];?>
<div class="modal fade" id="editPay<?=$p['id']?>"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h2 class="h5">Edit payment · <?=e($p['payment_for'])?></h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="edit_payment" value="1"><input type="hidden" name="payment_id" value="<?=$p['id']?>"><label class="form-label">Amount</label><input class="form-control mb-3" type="number" step=".01" min=".01" name="amount" value="<?=$p['amount']?>" required><label class="form-label">Payment date</label><input class="form-control mb-3" type="date" name="paid_at" value="<?=date('Y-m-d',strtotime($p['paid_at']))?>"><label class="form-label">Payment location</label><select class="form-select mb-3" name="location"><?php foreach(['DXB','MGQ'] as $l):?><option <?=$p['location']===$l?'selected':''?>><?=$l?></option><?php endforeach?></select><label class="form-label">Method</label><select class="form-select mb-3" name="method"><?php foreach(['Cash','Bank Transfer','Mobile Money','Card','Other'] as $m):?><option <?=$p['payment_method']===$m?'selected':''?>><?=$m?></option><?php endforeach?></select><label class="form-label">Deposit to bank account <small class="text-secondary">(required for Bank Transfer · optional for other methods — updates the bank statement)</small></label><select class="form-select mb-3" name="bank_account_id"><option value="">Cash / not linked to a bank</option><?php foreach($bankAccounts as $ba):if(is_admin()||in_array((int)$ba['branch_id'],$bankBranches,true)):?><option value="<?=$ba['id']?>" <?=(int)$p['bank_account_id']===(int)$ba['id']?'selected':''?>><?=e($ba['name'].' · '.$ba['bank_name'].' · '.$ba['account_number'].(!empty($ba['branch_name'])?' ('.$ba['branch_name'].')':''))?></option><?php endif;endforeach?></select><label class="form-label">Reference</label><input class="form-control mb-3" name="reference" value="<?=e($p['reference_no']?:'')?>"><label class="form-label">Notes</label><input class="form-control" name="notes" value="<?=e($p['notes']?:'')?>"></div><div class="modal-footer"><button class="btn btn-primary"><i class="bi bi-check-lg"></i> Save changes</button></div></form></div></div>
<?php endforeach;endif?>
<script>(function(){document.querySelectorAll('.modal .pay-extra').forEach(ex=>{const f=ex.closest('form'),amt=f&&f.querySelector('.pay-amount'),maxEl=ex.dataset.maxid?document.getElementById(ex.dataset.maxid):null,total=parseFloat(ex.dataset.total||0),paid=parseFloat(ex.dataset.paid||0);const up=()=>{const mx=Math.max(0,total+parseFloat(ex.value||0)-paid);if(amt)amt.max=mx.toFixed(2);if(maxEl)maxEl.textContent='USD '+mx.toFixed(2);};ex.addEventListener('input',up);up();});})();</script>
<?php require __DIR__.'/partials/footer.php';?>
