<?php
require __DIR__.'/bootstrap.php';
require_perm('reports.view');
$me=user();
$from=$_GET['from']??date('Y-m-01');
$to=$_GET['to']??date('Y-m-d');
$branches=is_admin()?$pdo->query('SELECT id,name,code FROM branches WHERE active=1 ORDER BY name')->fetchAll():[];
$branch=is_admin()?(int)($_GET['branch']??0):(int)require_branch();
$branchName=$branch>0?(string)($pdo->query('SELECT name FROM branches WHERE id='.(int)$branch)->fetchColumn()?:''):'';
/* Payments carry the shipment's branch; income_entries / expenses have their own. */
$payCond='';$payParams=[$from,$to];$incCond='';$incParams=[$from,$to];$expCond='';$expParams=[$from,$to];
if($branch>0){$payCond=' AND s.branch_id=?';$payParams[]=$branch;$incCond=' AND i.branch_id=?';$incParams[]=$branch;$expCond=' AND e.branch_id=?';$expParams[]=$branch;}
$st=$pdo->prepare("SELECT DATE(p.paid_at) d,p.amount,p.payment_method,p.reference_no,p.location,s.awb FROM payments p JOIN shipments s ON s.id=p.shipment_id WHERE DATE(p.paid_at) BETWEEN ? AND ?$payCond ORDER BY p.paid_at DESC");$st->execute($payParams);$payments=$st->fetchAll();
$st=$pdo->prepare("SELECT i.income_date d,i.amount,i.payment_method,i.reference_no,i.category,i.description,i.payer,s.awb FROM income_entries i LEFT JOIN shipments s ON s.id=i.shipment_id WHERE i.income_date BETWEEN ? AND ?$incCond ORDER BY i.income_date DESC");$st->execute($incParams);$manual=$st->fetchAll();
$st=$pdo->prepare("SELECT e.*,s.awb FROM expenses e LEFT JOIN shipments s ON s.id=e.shipment_id WHERE e.expense_date BETWEEN ? AND ?$expCond ORDER BY e.expense_date DESC");$st->execute($expParams);$expenses=$st->fetchAll();
$incomePay=(float)array_sum(array_column($payments,'amount'));
$incomeOther=(float)array_sum(array_column($manual,'amount'));
$income=$incomePay+$incomeOther;
$expense=(float)array_sum(array_column($expenses,'amount'));
$net=$income-$expense;
$margin=$income>0?($net/$income*100):0;
$incomeByCat=['Shipment payments'=>['n'=>count($payments),'amount'=>$incomePay]];
foreach($manual as $m){$c=$m['category'];if(!isset($incomeByCat[$c]))$incomeByCat[$c]=['n'=>0,'amount'=>0.0];$incomeByCat[$c]['n']++;$incomeByCat[$c]['amount']+=(float)$m['amount'];}
$expByCat=[];
foreach($expenses as $x){$c=$x['category'];if(!isset($expByCat[$c]))$expByCat[$c]=['n'=>0,'amount'=>0.0,'paid'=>0.0];$expByCat[$c]['n']++;$expByCat[$c]['amount']+=(float)$x['amount'];if($x['status']==='Paid')$expByCat[$c]['paid']+=(float)$x['amount'];}
if(($_GET['export']??'')==='csv'){header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="profit-loss-'.$from.'-'.$to.'.csv"');$o=fopen('php://output','w');fputcsv($o,['Profit & Loss report',$from,'to',$to]);fputcsv($o,['Summary','Amount']);fputcsv($o,['Income',number_format($income,2,'.','')]);fputcsv($o,['Expenses',number_format($expense,2,'.','')]);fputcsv($o,['Net profit / loss',number_format($net,2,'.','')]);fputcsv($o,[]);fputcsv($o,['TYPE','DATE','SOURCE','DETAILS','AWB','REFERENCE','METHOD','STATUS','AMOUNT']);foreach($payments as $r)fputcsv($o,['INCOME',$r['d'],'Shipment payment','Payment',''.$r['awb'],''.($r['reference_no']??''),$r['payment_method'],'Received',$r['amount']]);foreach($manual as $r)fputcsv($o,['INCOME',$r['d'],'Other income',$r['category'].' · '.$r['description'],''.($r['awb']??''),''.($r['reference_no']??''),$r['payment_method'],'Received',$r['amount']]);foreach($expenses as $r)fputcsv($o,['EXPENSE',$r['expense_date'],$r['category'],$r['description'],''.($r['awb']??''),'','',''.$r['status'],$r['amount']]);fclose($o);exit;}
$title='Profit & Loss';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h1 class="h3 fw-bold mb-1">Profit &amp; Loss</h1><p class="text-secondary mb-0">Faa'iido iyo khasaaro · income = shipment payments + other income entries.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="?<?=http_build_query(array_merge($_GET,['export'=>'csv']))?>"><i class="bi bi-download"></i> Export CSV</a><button class="btn btn-primary" onclick="print()"><i class="bi bi-printer"></i> Print / PDF</button></div></div>
<form class="card p-3 mb-4 d-print-none"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">From</label><input class="form-control" type="date" name="from" value="<?=e($from)?>"></div><div class="col-md-3"><label class="form-label">To</label><input class="form-control" type="date" name="to" value="<?=e($to)?>"></div><?php if(is_admin()):?><div class="col-md-3"><label class="form-label">Branch</label><select class="form-select" name="branch"><option value="0">All branches</option><?php foreach($branches as $br):?><option value="<?=$br['id']?>" <?=$branch===(int)$br['id']?'selected':''?>><?=e($br['name'].' ('.$br['code'].')')?></option><?php endforeach?></select></div><?php endif?><div class="col-md-3"><button class="btn btn-dark">Generate report</button></div></div><div class="row mt-2 d-print-none"><div class="col-12"><span class="text-secondary small me-2">Quick:</span><a class="btn btn-sm btn-outline-secondary me-1" href="?<?=http_build_query(array_merge($_GET,['from'=>date('Y-m-d'),'to'=>date('Y-m-d')]))?>">Today</a><a class="btn btn-sm btn-outline-secondary me-1" href="?<?=http_build_query(array_merge($_GET,['from'=>date('Y-m-d',strtotime('-6 days')),'to'=>date('Y-m-d')]))?>">Last 7 days</a><a class="btn btn-sm btn-outline-secondary me-1" href="?<?=http_build_query(array_merge($_GET,['from'=>date('Y-m-01'),'to'=>date('Y-m-d')]))?>">This month</a><a class="btn btn-sm btn-outline-secondary" href="?<?=http_build_query(array_merge($_GET,['from'=>date('Y-01-01'),'to'=>date('Y-m-d')]))?>">This year</a></div></div></form>
<div class="row g-3 mb-4"><?php foreach([['Income',money($income),'text-success','bi-cash-stack'],['Expenses',money($expense),'text-danger','bi-graph-down-arrow'],['Net profit / loss',money($net),$net>=0?'text-success':'text-danger','bi-currency-exchange'],['Margin',number_format($margin,1).'%',$margin>=0?'text-success':'text-danger','bi-percent']] as [$l,$v,$cl,$ic]):?><div class="col-6 col-lg-3"><div class="card p-4"><div class="d-flex align-items-center gap-2 mb-2"><i class="bi <?=$ic?> text-secondary"></i><small class="text-secondary"><?=e($l)?></small></div><strong class="h4 <?=$cl?>"><?=e($v)?></strong></div></div><?php endforeach?></div>
<div class="row g-4"><div class="col-lg-6"><div class="card p-3 p-lg-4 mb-4"><h2 class="h5 mb-3">Income breakdown</h2><div class="table-responsive"><table class="table"><thead><tr><th>Category</th><th class="text-end">Entries</th><th class="text-end">Amount</th></tr></thead><tbody><?php $rc=0;foreach($incomeByCat as $c=>$x):$rc++;?><tr<?php if($rc===count($incomeByCat)):?> class="fw-bold"<?php endif?>><td><?=e($c)?></td><td class="text-end"><?=$x['n']?></td><td class="text-end text-success"><?=money($x['amount'])?></td></tr><?php endforeach?><tr class="fw-bold border-top"><td>Total income</td><td class="text-end"><?=count($payments)+count($manual)?></td><td class="text-end text-success"><?=money($income)?></td></tr></tbody></table></div></div><div class="card p-3 p-lg-4"><h2 class="h5 mb-3">Income transactions</h2><input class="form-control mb-3 d-print-none" style="max-width:300px" data-search-for="#plIncomeTable" placeholder="Search income…"><div class="table-responsive"><table class="table" id="plIncomeTable"><thead><tr><th>Date</th><th>Source</th><th>Details</th><th>Ref</th><th class="text-end">Amount</th></tr></thead><tbody><?php foreach($payments as $r):?><tr><td><?=app_date($r['d'])?></td><td><span class="badge text-bg-success">Shipment payment</span></td><td><?=e($r['awb'])?><small class="d-block text-secondary"><?=e($r['location'])?> · <?=e($r['payment_method'])?></small></td><td><?=e($r['reference_no']?:'—')?></td><td class="text-end text-success fw-bold"><?=money($r['amount'])?></td></tr><?php endforeach?><?php foreach($manual as $r):?><tr><td><?=app_date($r['d'])?></td><td><span class="badge text-bg-light border"><?=e($r['category'])?></span></td><td><?=e($r['description'])?><?php if($r['awb']):?><small class="d-block text-secondary">AWB <?=e($r['awb'])?></small><?php endif?></td><td><?=e($r['reference_no']?:'—')?></td><td class="text-end text-success fw-bold"><?=money($r['amount'])?></td></tr><?php endforeach?><?php if(!$payments&&!$manual):?><tr><td colspan="5" class="text-center text-secondary py-4">No income in this period.</td></tr><?php endif?></tbody></table></div></div></div>
<div class="col-lg-6"><div class="card p-3 p-lg-4 mb-4"><h2 class="h5 mb-3">Expense breakdown</h2><div class="table-responsive"><table class="table"><thead><tr><th>Category</th><th class="text-end">Entries</th><th class="text-end">Total</th><th class="text-end">Paid</th></tr></thead><tbody><?php foreach($expByCat as $c=>$x):?><tr><td><?=e($c)?></td><td class="text-end"><?=$x['n']?></td><td class="text-end"><?=money($x['amount'])?></td><td class="text-end text-success"><?=money($x['paid'])?></td></tr><?php endforeach?><tr class="fw-bold border-top"><td>Total expenses</td><td class="text-end"><?=count($expenses)?></td><td class="text-end text-danger"><?=money($expense)?></td><td class="text-end text-success"><?=money(array_sum(array_map(fn($x)=>$x['status']==='Paid'?(float)$x['amount']:0,$expenses)))?></td></tr></tbody></table></div></div><div class="card p-3 p-lg-4"><h2 class="h5 mb-3">Expense transactions</h2><input class="form-control mb-3 d-print-none" style="max-width:300px" data-search-for="#plExpenseTable" placeholder="Search expenses…"><div class="table-responsive"><table class="table" id="plExpenseTable"><thead><tr><th>Date</th><th>Category</th><th>Details</th><th>Vendor</th><th>Status</th><th class="text-end">Amount</th></tr></thead><tbody><?php foreach($expenses as $r):?><tr><td><?=app_date($r['expense_date'])?></td><td><?=e($r['category'])?></td><td><?=e($r['description'])?><?php if($r['awb']):?><small class="d-block text-secondary">AWB <?=e($r['awb'])?></small><?php endif?></td><td><?=e($r['vendor']?:'—')?></td><td><span class="badge text-bg-<?=$r['status']==='Paid'?'success':($r['status']==='Overdue'?'danger':'warning')?>"><?=e($r['status'])?></span></td><td class="text-end text-danger fw-bold"><?=money($r['amount'])?></td></tr><?php endforeach?><?php if(!$expenses):?><tr><td colspan="6" class="text-center text-secondary py-4">No expenses in this period.</td></tr><?php endif?></tbody></table></div></div></div></div>
<p class="text-secondary small mt-3">Report period: <?=app_date($from)?> – <?=app_date($to)?> · <?=e($branchName!==''?('Branch: '.$branchName):'All branches')?> · <?=money($income)?> income − <?=money($expense)?> expenses = <strong class="<?=$net>=0?'text-success':'text-danger'?>"><?=money($net)?></strong></p>
<script>(function(){document.querySelectorAll('[data-search-for]').forEach(inp=>{const table=document.querySelector(inp.dataset.searchFor);if(!table)return;inp.addEventListener('input',()=>{const q=inp.value.trim().toLowerCase();table.querySelectorAll('tbody tr').forEach(r=>r.hidden=q!==''&&!r.innerText.toLowerCase().includes(q))})})})();</script>
<?php require __DIR__.'/partials/footer.php';?>