<?php
require __DIR__.'/bootstrap.php';
require_perm('reports.view');
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-d');$airline=$_GET['airline']??'';
$params=[$from,$to];$filters='';
if($airline!==''){$filters.=' AND s.airline_id=?';$params[]=$airline;}
if(!is_admin())$filters.=' AND s.branch_id='.(int)require_branch();
$s=$pdo->prepare("SELECT COUNT(*) shipments,COALESCE(SUM(s.pcs),0) pcs,COALESCE(SUM(s.kg),0) kg,COALESCE(SUM(s.total),0) revenue,COALESCE(SUM(s.paid_dxb),0) paid,COALESCE(SUM(s.balance_mgq),0) outstanding FROM shipments s WHERE s.shipment_date BETWEEN ? AND ? AND s.status<>'Cancelled'$filters");$s->execute($params);$totals=$s->fetch();
$s=$pdo->prepare("SELECT a.name,a.code,COUNT(*) shipments,SUM(s.pcs) pcs,SUM(s.kg) kg,SUM(s.total) revenue,SUM(s.balance_mgq) outstanding FROM shipments s JOIN airlines a ON a.id=s.airline_id WHERE s.shipment_date BETWEEN ? AND ? AND s.status<>'Cancelled'$filters GROUP BY a.id ORDER BY kg DESC");$s->execute($params);$byAirline=$s->fetchAll();
$airlines=$pdo->query('SELECT * FROM airlines WHERE active=1 ORDER BY name')->fetchAll();
$outstanding=$pdo->prepare("SELECT s.*,a.code airline FROM shipments s JOIN airlines a ON a.id=s.airline_id WHERE s.shipment_date BETWEEN ? AND ? AND s.balance_mgq>0 AND s.status<>'Cancelled'$filters ORDER BY s.balance_mgq DESC");$outstanding->execute($params);$outstanding=$outstanding->fetchAll();
if(($_GET['export']??'')==='csv'){header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="cargo-report-'.$from.'-'.$to.'.csv"');$o=fopen('php://output','w');fputcsv($o,['Airline','Shipments','Pieces','KG','Revenue','Outstanding MGQ']);foreach($byAirline as $r)fputcsv($o,[$r['name'],$r['shipments'],$r['pcs'],$r['kg'],$r['revenue'],$r['outstanding']]);fclose($o);exit;}
$title='Reports';require __DIR__.'/partials/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h1 class="h3 fw-bold mb-1">Cargo reports</h1><p class="text-secondary mb-0"><?=is_admin()?'All branches':'Your branch only'?> · daily and monthly summaries.</p></div><div><a class="btn btn-outline-primary" href="?<?=http_build_query(array_merge($_GET,['export'=>'csv']))?>">Export CSV</a><button class="btn btn-primary" onclick="print()">Print / PDF</button></div></div>
<form class="card p-3 mb-4 d-print-none"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">From</label><input class="form-control" type="date" name="from" value="<?=e($from)?>"></div><div class="col-md-3"><label class="form-label">To</label><input class="form-control" type="date" name="to" value="<?=e($to)?>"></div><div class="col-md-3"><label class="form-label">Airline</label><select class="form-select" name="airline"><option value="">All airlines</option><?php foreach($airlines as $a):?><option value="<?=$a['id']?>" <?=$airline==$a['id']?'selected':''?>><?=e($a['name'])?></option><?php endforeach?></select></div><div class="col-md-3"><button class="btn btn-dark">Generate report</button></div></div></form>
<div class="row g-3 mb-4"><?php foreach([['Shipments',$totals['shipments']],['Pieces',$totals['pcs']],['Cargo KG',number_format((float)$totals['kg'],2)],['Outstanding',money($totals['outstanding'])]] as [$l,$v]):?><div class="col-6 col-lg-3"><div class="card p-4"><small class="text-secondary"><?=e($l)?></small><strong class="h4 mt-1"><?=e($v)?></strong></div></div><?php endforeach?></div>
<div class="card p-4 mb-4"><h2 class="h5 mb-3">Airline shipment summary</h2><div class="table-responsive"><table class="table"><thead><tr><th>Airline</th><th>Shipments</th><th>PCS</th><th>KG</th><th>Revenue</th><th>Outstanding</th></tr></thead><tbody><?php foreach($byAirline as $r):?><tr><td class="fw-semibold"><?=e($r['name'])?> (<?=e($r['code'])?>)</td><td><?=e($r['shipments'])?></td><td><?=e($r['pcs'])?></td><td><?=number_format((float)$r['kg'],2)?></td><td><?=money($r['revenue'])?></td><td class="text-danger"><?=money($r['outstanding'])?></td></tr><?php endforeach?></tbody></table></div></div>
<div class="card p-4"><h2 class="h5 mb-3">Outstanding balances</h2><div class="table-responsive"><table class="table"><thead><tr><th>AWB</th><th>Sender</th><th>Airline</th><th>Total</th><th>Paid DXB</th><th>Balance MGQ</th></tr></thead><tbody><?php foreach($outstanding as $r):?><tr><td class="fw-semibold"><?=e($r['awb'])?></td><td><?=e($r['sender'])?></td><td><?=e($r['airline'])?></td><td><?=money($r['total'])?></td><td><?=money($r['paid_dxb'])?></td><td class="fw-bold text-danger"><?=money($r['balance_mgq'])?></td></tr><?php endforeach?></tbody></table></div></div>
<?php require __DIR__.'/partials/footer.php';?>
